language: python

# cache pip dependency
cache: pip

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest -c -v --failfast


notifications:
  email:
    on_success: change
    on_failure: always

# after_success:
#   - pip install python-coveralls && coveralls
