#!/usr/bin/env python
# coding: utf-8

import os
import sys
import logging

import yaml

import k3log
from k3fs import fread
from k3fs import fwrite
from k3git import GitOpt
from k3git import Git
from k3handy import cmd0
from k3handy import cmdx
from k3handy import dd
from k3handy import display
from k3handy import pabs
from k3handy import pjoin
from k3handy import prebase
from k3proc import CalledProcessError

version = '0.1.0'
conffn = ".gift"
refsfn = ".gift-refs"
superref = "refs/remotes/super/head"

logger = logging.getLogger(__name__)


class GiftError(Exception):
    def __init__(self, msg):
        super(GiftError, self).__init__(msg)
        self.returncode = 2
        self.out = []
        self.err = [msg]


class Gift(object):
    """
    """

    # inside gitdir:
    sub_gitdir_fmt = "gift/subdir/{dir}"

    def __init__(self, opt):
        self.gitopt = opt.clone()
        if self.gitopt.opt.get('exec_path') is None:
            self.gitpath = 'git'
        else:
            self.gitpath = pjoin(self.gitopt.opt['exec_path'], 'git')
        self.in_git_dir = False

        # When multiple -C options are given, each subsequent non-absolute -C
        # <path> is interpreted relative to the preceding -C <path>.

        st = pabs(".")
        for p in self.gitopt.opt['startpath']:
            st = prebase(st, p)

        self.startpath = st
        self.cwd = self.startpath
        # Git objects run in self.cwd, so passing -C to git would apply it twice
        self.gitopt.opt['startpath'] = []

        # As in git, --git-dir and --work-tree override GIT_DIR and GIT_WORK_TREE
        git_dir = self.gitopt.opt['git_dir']
        if git_dir is None:
            git_dir = os.environ.get('GIT_DIR')

        work_tree = self.gitopt.opt['work_tree']
        if work_tree is None:
            work_tree = os.environ.get('GIT_WORK_TREE')

        self.git_dir = prebase(self.startpath, git_dir)
        self.working_dir = prebase(self.startpath, work_tree)

    def init_git_config(self):

        git_dir_specified = self.git_dir is not None

        if self.git_dir is None:
            try:
                self.git_dir = cmd0(self.gitpath, "rev-parse", "--absolute-git-dir", cwd=self.cwd)
                dd("git_dir:", self.git_dir)
            except CalledProcessError:
                dd("not in a git dir")

        dd("git_dir:", self.git_dir)

        if self.git_dir is None:
            return

        if (self.cwd.startswith(self.git_dir + '/')
                or self.git_dir == self.cwd):
            self.in_git_dir = True

        if self.in_git_dir:
            return

        # git rev-parse --show-toplevel:
        # - With --git-dir=xx, it always returns current dir.
        # - Without --git-dir=xx, it might fail if cwd is not in a git repo
        if git_dir_specified:
            if self.working_dir is None:
                self.working_dir = self.cwd
            else:
                pass
        else:
            if self.working_dir is None:
                self.working_dir = cmd0(self.gitpath, "rev-parse", "--show-toplevel", cwd=self.cwd)

        dd("working_dir:", self.working_dir)

        self.confpath = self.working_dir + '/' + conffn
        self.conf = self.parse()

    def parse_remote(self, subdir, remo):
        usage = "{}: {}: expect <url>@<branch>, got: {!r}".format(conffn, subdir, remo)
        if not isinstance(remo, str):
            raise GiftError(usage)

        elts = remo.rsplit("@", 1)
        if len(elts) != 2:
            raise GiftError(usage)

        # An ssh url without a branch splits at "git@"; a branch name has no ":"
        if elts[1] == '' or ':' in elts[1]:
            raise GiftError(usage)

        return ["origin", elts[0], elts[1]]

    def read_conf(self):
        try:
            with open(self.confpath, 'r') as f:
                cont = f.read()
        except OSError:
            return {
                "dirs": {}
            }
        yml = yaml.safe_load(cont)
        return yml

    def parse(self):

        yml = self.read_conf()

        # rm = yml.get("remotes", {})
        dirs = yml["dirs"]

        for k in dirs:
            ups = self.parse_remote(k, dirs[k])

            # A relative url is relative to the super repo root, where .gift
            # is, but git resolves it against the cwd of each git process
            url = ups[1]
            if url.startswith(("./", "../")):
                url = os.path.normpath(pjoin(self.working_dir, url))

            sub_gitdir = self.sub_gitdir_fmt.format(dir=k)
            dirs[k] = {
                "dir": k,
                "upstream": {
                    "name": ups[0],
                    "url": url,
                    "branch": ups[2],
                },
                "refhead": "refs/gift/sub/{dir}".format(dir=k),
                "sub_gitdir": sub_gitdir,
                "env": {
                    "GIT_DIR": pjoin(self.git_dir, sub_gitdir),
                    "GIT_WORK_TREE": pjoin(self.working_dir, k),
                    # "GIT_OBJECT_DIRECTORY": pjoin(self.git_dir, "objects"),
                },
                "bareenv": {
                    "GIT_DIR": pjoin(self.git_dir, sub_gitdir),
                },
            }

        return yml

    def _g(self, what="", bare=False):
        if what == '':
            return Git(
                self.gitopt,
                gitpath=self.gitpath,
                cwd=self.cwd,
            )

        if isinstance(what, str):
            sb = self.conf["dirs"][what]
        else:
            sb = what

        git_dir = sb["env"]["GIT_DIR"]
        working_dir = sb["env"]["GIT_WORK_TREE"]

        if bare:
            return Git(
                self.gitopt,
                gitpath=self.gitpath,
                gitdir=git_dir,
                cwd=self.cwd,
                ctxmsg='GIFT: ' + sb['dir'],
            )
        else:
            return Git(
                self.gitopt,
                gitpath=self.gitpath,
                gitdir=git_dir,
                working_dir=working_dir,
                cwd=self.cwd,
                ctxmsg='GIFT: ' + sb['dir'],
            )

    def check_worktree(self, sb):
        self.try_init_sub_git(sb)
        self.try_init_sub_worktree(sb)

    def try_init_sub_git(self, sb):

        wtgpath = pjoin(self.git_dir, sb["sub_gitdir"])

        bareenv = sb['bareenv']
        up = sb["upstream"]

        if not os.path.isdir(wtgpath):
            cmdx(self.gitpath, "init", "--bare", "--initial-branch=" + up["branch"], bareenv["GIT_DIR"])
        else:
            dd("gitdir exist:", wtgpath)

        g = self._g(sb, bare=True)
        # The url as configured: `git remote get-url` expands url.<base>.insteadOf
        u = g.cmdf("config", "--get", "remote." + up["name"] + ".url", flag='n0')
        if u is None:
            dd("remote not found, add:", up)
            g.out(2, "add remote:", up["name"], up["url"])
            g.remote_add(up["name"], up["url"], capture=False)
        elif u != up["url"]:
            g.out(2, "set remote url:", up["name"], up["url"])
            g.cmdf("remote", "set-url", up["name"], up["url"], flag='x')

        r = g.rev_of(up["name"] + '/' + up["branch"])
        if r is None:
            dd("remote head not found:", up["name"] + '/' + up["branch"])
            dd("need fetch")
            g.out(2, "fetch", up["name"], up["url"])
            g.fetch(up["name"], flag='xp')

    def try_init_sub_worktree(self, sb):

        path = sb['env']["GIT_WORK_TREE"]
        if not os.path.isdir(path):
            os.makedirs(path, mode=0o755)

        g = self._g(sb)
        if g.rev_of("HEAD") is None:
            dd("HEAD not found:")

            up = sb['upstream']

            # If .gift-refs records a commit for this dir, the super repo has
            # already checked out its files: adopt it and keep the files.
            refs = []
            statep = pjoin(self.working_dir, refsfn)
            if os.path.isfile(statep):
                cont = fread(statep)
                refs = yaml.safe_load(cont)

            recorded = dict(refs).get(sb['dir'])
            if recorded is None:
                g.checkout(up["branch"])
            elif g.obj_type(recorded) is None:
                msg = "{}: can not find commit {} recorded in {}; push it to {} from the clone that made it"
                raise GiftError(msg.format(sb['dir'], recorded, refsfn, up['name']))
            else:
                upstream = up['name'] + '/' + up['branch']
                g.reset_to_commit('mixed', recorded)
                g.cmdf('branch', '--set-upstream-to=' + upstream, flag='x')

    def get_subrepo_config(self, subdir):

        # TODO test subdir not in working_dir?
        working_dir = self.working_dir
        subdir = os.path.abspath(subdir)

        dd("working_dir:", working_dir)
        dd("subdir:", subdir)

        rel = os.path.relpath(subdir, working_dir)
        if rel.startswith('..'):
            dd("subdir is not in working_dir")
            return '', None

        dd("conf:", self.conf["dirs"])

        while rel != '':
            dd("reldir:", rel)
            if rel in self.conf["dirs"]:
                return rel, self.conf["dirs"][rel]

            # trim last part.
            rel, _ = os.path.split(rel)
        else:
            return '', None

    def exec_informative_cmd(self, cmds):
        cmd = cmds[0]
        if cmd == '--version':
            display(1, "gift version " + version)
            self._g().cmdf('--version', flag='xp')
        elif cmd == '--help':
            self._g().cmdf('--help', flag='xp')
            lines = [
                "",
                "Gift extended command:",
                "",
                "gift clone --sub <url>@<branch> <dir>",
                "    Add a sub-repo to <dir> by clone it from <url>, and checkout <branch>",
                "",
                "gift commit --sub [-m <msg>]",
                "    Add all sub-repo to super-repo and commit",
                "",
            ]
            # TODO finish them
            for l in lines:
                display(1, l)
        elif cmd in ('--exec-path',
                     '--man-path',
                     '--info-path',
                     '--html-path',
                     ):
            self._g().cmdf(cmd, flag='xp')

    def cmd(self, cmds):

        dd("gift cmd:", cmds)

        # If a command does not need to be run inside a git repo, delegate it
        # and quit.
        if cmds[0] == "init" and '--sub' not in cmds:
            # delegate to original git
            self._g().cmdf(*cmds, flag='xp')
            return

        self.init_git_config()

        if self.git_dir is None:
            self._g().cmdf(*cmds, flag='xp')
            return

        cmd, issub, cmds = self._arg_param(cmds)

        # A parse error is reported by the read after the command
        refs0 = self._get_head_refs(warn=False)

        if self.in_git_dir:
            if issub:
                raise GiftError("--sub can not be used in git-dir:" + self.git_dir)
            else:
                g = self._g().cmdf(*cmds, flag='xp')
        else:

            subdir = self.cwd
            subdir, sb = self.get_subrepo_config(subdir)
            dd("subdir:", subdir, sb)

            if sb is not None:
                self.check_worktree(sb)

            # TODO nested?
            if issub:

                if cmd == "init":
                    return self.x_init_sub(cmds)
                if cmd == "clone":
                    return self.x_clone_sub(cmds)
                elif cmd == 'commit':
                    return self.x_commit_sub(cmds)
                elif cmd == 'fetch':
                    return self.x_fetch_sub(cmds)
                elif cmd == 'merge':
                    return self.x_merge_sub(cmds)
                elif cmd == 'reset':
                    return self.x_reset_sub(cmds)

                raise GiftError("--sub is not supported for: " + cmd)

            if sb is not None:
                g = self._g(sb)
                g.cmdf(*cmds, flag='xp')
            else:
                g = self._g()
                g.cmdf(*cmds, flag='xp')
                # TODO run gift in a git-dir

        refs1 = self._get_head_refs(warn=True)
        if refs0 != refs1 and refs1 is not None:
            # A checkout or pull may have changed .gift
            self.conf = self.parse()
            self._populate_ref(refs1)

    def _arg_param(self, cmds):

        cmd = cmds[0]
        cmds = cmds[1:]

        if '--' in cmds:
            i = cmds.index('--')
            args = cmds[:i]
        else:
            args = cmds

        issub = '--sub' in args
        if issub:
            cmds.remove('--sub')

        return cmd, issub, [cmd] + cmds

    def _get_head_refs(self, warn):
        # Sub-repo config is not loaded in a git-dir, and without .gift there
        # is no sub-repo: skip the git process
        if self.in_git_dir or not os.path.isfile(self.confpath):
            return None

        g = self._g()
        try:
            lines = g.cmdf("show", "HEAD:" + refsfn, flag='xo')
        except CalledProcessError:
            return None

        cont = "\n".join(lines)
        try:
            return yaml.safe_load(cont)
        except yaml.YAMLError as e:
            if warn:
                display(2, ["GIFT: can not parse " + refsfn + " in HEAD:", str(e)])
            return None

    def x_clone_sub(self, cmds):

        # TODO test remove is gift clone --sub ssh://git@github.com/openacid/celeritasdb.wiki wiki
        # there is a "@" in it.
        #
        # TODO test ".gift" without "remotes"
        # TODO test clone --sub
        remote = cmds[1]
        subdir = cmds[2]
        # TODO overwrite existent conf?

        y = self.read_conf()
        y["dirs"][subdir] = remote
        cont = yaml.dump(y, default_flow_style=False)
        fwrite(self.confpath, cont)
        self.init_git_config()

        g = self._g()
        g.cmdf("add", self.confpath, flag='x')
        g.cmdf("commit", self.confpath, "-m", "add sub repo: " + remote + " in " + subdir, flag='x')

        self.x_init_sub([])
        self.x_commit_sub([])

    def x_init_sub(self, cmds):
        for sub in self.conf["dirs"]:
            sb = self.conf["dirs"][sub]
            self.check_worktree(sb)

        try:
            cont = fread(pjoin(self.working_dir, refsfn))
        except IOError:
            # TODO message
            pass
        else:
            refs = yaml.safe_load(cont)
            self._populate_ref(refs)

    def x_commit_sub(self, cmds):
        args = cmds[1:]
        msg = "commit subdirs"
        if len(args) == 2 and args[0] == "-m":
            msg = args[1]
        elif args != []:
            raise GiftError("commit --sub accepts only -m <msg>, got: " + " ".join(args))

        g = self._g()
        headtree = g.tree_of("HEAD", flag='x')
        supertree = headtree
        parent = g.rev_of("HEAD")
        refs = []
        paths = []
        for sub in self.conf["dirs"]:
            sb = self.conf["dirs"][sub]
            self.check_worktree(sb)
            supertree, commithash = self._add_sub(supertree, sb)
            refs.append([sb["dir"], commithash])
            paths.append(pjoin(self.working_dir, sb["dir"]))

            # Other clones fetch sub-repo commits only from the remote
            remote = sb["upstream"]["name"]
            sg = self._g(sb, bare=True)
            pushed = sg.cmdf("for-each-ref", "--contains", commithash, "refs/remotes/" + remote, flag='xo')
            if pushed == []:
                sg.out(2, "warning: commit", commithash, "is not pushed to", remote + ",",
                       "so other clones can not check it out")

        refs = sorted(refs)
        cont = yaml.dump(refs, default_flow_style=False)
        statep = pjoin(self.working_dir, refsfn)
        fwrite(statep, cont)

        statehash = g.blob_new(statep, flag='x')
        supertree = g.tree_add_obj(supertree, refsfn, statehash)

        if supertree == headtree:
            display(2, "GIFT: nothing to commit: no sub-repo changed")
            return

        newcommit = g.cmdf("commit-tree", "-p", parent, supertree, input=msg, flag='x0')

        # Keep other staged changes: reset only the paths this commit changed
        g.cmdf("reset", newcommit, "--", statep, *paths, flag='x')
        g.cmdf("update-ref", "-m", "commit subdirs", "HEAD", newcommit, parent, flag='x')

        self._populate_ref(refs)

    def x_fetch_sub(self, cmds):
        for sub in self.conf["dirs"]:
            sb = self.conf["dirs"][sub]
            self.check_worktree(sb)
            _, out, err = cmdx(self.gitpath, "fetch", sb["upstream"]["name"], env=sb["env"])
            display(out, err)

    def x_merge_sub(self, cmds):
        # only ff-only allowed
        for sub in self.conf["dirs"]:
            sb = self.conf["dirs"][sub]
            self.check_worktree(sb)
            _, out, err = cmdx(self.gitpath, "merge", "--ff-only", env=sb["env"])
            display(out, err)

    def x_reset_sub(self, cmds):
        candidate_args = ['--soft',
                          '--mixed',
                          '-N',
                          '--hard',
                          '--merge',
                          '--keep',
                          '-q',
                          '--quiet', ]
        args = []
        for c in candidate_args:
            if c in cmds:
                args.append(c)

        for sub in self.conf["dirs"]:
            sb = self.conf["dirs"][sub]
            self.check_worktree(sb)
            _, out, err = cmdx(self.gitpath, "reset", *args, superref, env=sb["env"])
            display(out, err)

    def _populate_ref(self, refs):

        for subdir, hsh in refs:
            sb = self.conf["dirs"].get(subdir)
            if sb is None:
                continue

            # Not initialized yet: `gift init --sub` populates it
            if not os.path.isdir(sb["env"]["GIT_DIR"]):
                continue

            try:
                cmdx(self.gitpath, "update-ref", superref, hsh, env=sb["env"])
            except CalledProcessError as e:
                g = self._g(sb, bare=True)
                g.out(2, "can not update", superref, "to", hsh)
                display(e.out, e.err)

    def _add_sub(self, supertree, sb):
        g = self._g()

        g.cmdf("fetch", sb["env"]["GIT_DIR"], "+HEAD:" + sb["refhead"], flag='x')

        sub_tree = g.tree_of(sb["refhead"], flag='x')
        supertree = g.tree_add_obj(supertree, sb["dir"], sub_tree)

        return supertree, g.rev_of(sb["refhead"])


def git_args():
    args = sys.argv[1:]

    gitopt = GitOpt().parse_args(args, {'--gift-verbose': True})

    verbose = 0
    v = os.environ.get('GIFT_VERBOSE')
    if v is not None:
        verbose = int(v)

    if '--gift-verbose' in gitopt.additional:
        verbose = 1

    return gitopt, verbose, gitopt.cmds


if __name__ == "__main__":
    gitopt, verbose, cmds = git_args()

    dd("gift opt:", gitopt.opt)
    dd("gift cmds:", cmds)
    # TODO need to pass opt to delegated command
    # TODO test change remote/up['branch'] then init again.
    # TODO git box received a unexpected GIT_DIR env.
    # TODO test command such "git box": git-box: git rev-parse --git-dir
    gift = Gift(gitopt)

    lvl = logging.INFO
    if verbose > 0:
        lvl = logging.DEBUG

    k3log.make_logger(
            fmt= '[%(asctime)s,%(filename)s,%(lineno)d,%(levelname)s] %(message)s',
            level=lvl)

    if cmds == [] and len(gitopt.informative_cmds) == 0:
        gift.exec_informative_cmd(['--help'])
        sys.exit(1)

    if cmds != [] and cmds[0] == 'gift-debug':
        display(1, ' '.join(cmds))
        display(1, yaml.dump({"opt": gitopt.opt,
                           "informative_cmds": gitopt.informative_cmds,
                           "additional": gitopt.additional},
                          default_flow_style=False))
        display(1, "evaluated cwd: " + str(gift.cwd))
        display(1, "evaluated git_dir: " + str(gift.git_dir))
        display(1, "evaluated working_dir: " + str(gift.working_dir))
        sys.exit(0)

    try:
        if len(gitopt.informative_cmds) > 0:
            gift.exec_informative_cmd(list(gitopt.informative_cmds))
        else:
            gift.cmd(cmds)
    except CalledProcessError as e:
        display(e.out, e.err)
        sys.exit(e.returncode)
    except GiftError as e:
        display(e.out, e.err)
        sys.exit(e.returncode)
    except KeyboardInterrupt:
        display(2, "user interrupted")
        sys.exit(1)
